[pytest]
testpaths = tests
addopts = --html=reports/report.html --self-contained-html
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %H:%M:%S
markers =
    smoke: pruebas críticas rápidas
    regression: suite completa de pruebas
    negative: casos de error y validación
    critical: flujos de negocio principales